package org.pardus.manager.controls.remotemanagement;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.control.TextField;
import javafx.scene.layout.GridPane;
import javafx.stage.FileChooser;
import javafx.stage.Modality;
import javafx.stage.Stage;
import javafx.stage.FileChooser.ExtensionFilter;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;

import org.pardus.manager.controls.common.LoginResult;
import org.pardus.manager.helper.MessageBox;
import org.pardus.manager.model.NetworkItem;
import org.pardus.manager.model.NetworkItemList;

import javafx.event.ActionEvent;
import javafx.scene.Scene;
import javafx.scene.control.TextArea;

public class RMExecuteScriptController extends GridPane {
	@FXML
	private TextArea tScript;
	@FXML
	private TextArea tConsole;
	@FXML
	private TextField tParams;

	private LoginResult loginResult;
	private NetworkItem item;
	private Stage s;

	public RMExecuteScriptController(NetworkItem item,LoginResult loginResult) {
		this.loginResult = loginResult;
		this.item = item;
		
		FXMLLoader loader = new FXMLLoader(getClass().getResource("RMExecuteScript.fxml"));
		loader.setController(this);
		loader.setRoot(this);
		try {
			loader.load();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	// Event Listener on Hyperlink.onAction
	@FXML
	public void ACLoadScriptFromFile(ActionEvent event) {
		FileChooser f = new FileChooser();

		f.setTitle("Dosya seçin");
		f.getExtensionFilters().add(new ExtensionFilter("Script dosyalarý", "*.sh", "*.bat", "*.cmd"));
		f.getExtensionFilters().add(new ExtensionFilter("Tüm dosyalar", "*.*"));
		File file = f.showOpenDialog(null);
		if (file != null) {
			try {
				byte[] bytes = Files.readAllBytes(file.toPath());
				String s = new String(bytes , "UTF-8");
				tScript.setText(s);
			} catch (IOException e) {
				MessageBox.Error(e.getMessage(), "Yükleme esnasýnda hata");
				e.printStackTrace();
			}
		}
	}

	// Event Listener on Button.onAction
	@FXML
	public void ACExecuteScript(ActionEvent event) {
		// TODO Autogenerated
	}

	public void ShowModal() {
		s = new Stage();
		s.setTitle(String.format("Betik çalýþtýr (%s - %s)", item.getHostName(), item.getIpAddr()));
		Scene scene = new Scene(this, 800, 400);
		s.setScene(scene);
//		s.initOwner(this);
		s.initModality(Modality.APPLICATION_MODAL);

//		s.show();
		s.showAndWait();
		
	}
}
