package org.pardus.manager.controls;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.layout.FlowPane;

import java.io.IOException;

import org.pardus.manager.model.NetworkItem;

import javafx.event.ActionEvent;

public class UCManageClientController extends FlowPane {

	private NetworkItem item;



	// Event Listener on Button.onAction
	@FXML
	public void ACChangeHostName(ActionEvent event) {
		// TODO Autogenerated
	}
	
	
	
	public UCManageClientController(NetworkItem item) {
		this.item = item;
		 try {
	            FXMLLoader loader = new FXMLLoader(getClass().getResource("UCManageClient.fxml"));
	            loader.setController(this);
	            loader.setRoot(this);
	            loader.load();
	        } catch (IOException exc) {
	            // handle exception
	        }
	}
}
